version: '3.8'
services:
  mongo:
    image: mongo:3.6.22-xenial
    ports:
      - '27017:27017'
    networks:
      - NextTripGo
    volumes:
      - mongo-data:/data/db
  server:
    image: server
    ports:
      - '4000:4000'
    networks:
      - NextTripGo
    depends_on:
      - mongo
  client:
    image: client
    stdin_open: true
    depends_on:
      - server
    ports:
      - '3000:3000'
    networks:
      - NextTripGo
networks:
  NextTripGo:
    driver: bridge
volumes:
  mongo-data:
    driver: local
